export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const CONTINUE_ORDER = 'CONTINUE_ORDER';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SENDING_PROCESS = 'SENDING_PROCESS';